#!/bin/sh

ret=0

#
# Check that we have no tabs or trailing spaces in the source code
#
failure=0
for dir in src tools; do
  pushd ../$dir >/dev/null
  for x in $(make -s echo-sources); do
    case "$x" in
     *.c|*.cpp|*.h|*.m) ;;
     *) continue ;;
    esac
    if grep '[[:space:]]$' "$x" >/dev/null 2>&1; then
      echo "error: $dir/$x contains trailing spaces"
      failure=1
    fi
    if grep '	' "$x" >/dev/null 2>&1; then
      echo "error: $dir/$x contains tabs"
      failure=1
    fi
  done
  popd >/dev/null
done
if test "$failure" != "0"; then
  ret=1
else
  echo "0 errors in source code"
fi

if test "$ret" != "0"; then
  exit 1
fi

exit 0

